### ISSUE TITLE
Можно и вот так

### ISSUE THREAD

**Issue by ArChIvExGaMexD** [NullGuy-dev/hogopy#1]
`import os
import sys
def foundMainFile():
    allFiles = os.listdir()
    for obj in allFiles:
        #If you compiled this code in EXE, remove the line below, and insert: if (obj == "your_main_file(exe)_name.exe"):")
        if (obj == "main.py"):
            return True
    return False
while True:
    if foundMainFile():
        #If you compiled this code in EXE, remove the line below, and insert: os.system("del your_main_file(exe)_name.exe")
        os.remove("main.py")
        break
sys.exit()`

**Comment by NullGuy-dev** [comment]
можно, но проект старый, поэтому не стоит внимания
